### ISSUE TITLE
新規登録APIからユーザーを作成できるようにする

### ISSUE THREAD

**Issue by NAKKA-K** [NAKKA-K/bookbok#119]

**Comment by oya0831** [comment]
![image](https://user-images.githubusercontent.com/25961633/49779721-cc337180-fd4e-11e8-99c2-b17358b6a4d0.png)
なぜかこのエラーが出る・・・これってsubmitボタン押したら何もエラーでないよね？

**Comment by oya0831** [comment]
![image](https://user-images.githubusercontent.com/25961633/49779751-ef5e2100-fd4e-11e8-9057-3c691533c436.png)
あとこの警告で<label for~></label>になってるところがあったんだけどhtmlForに直した方がいい？

**Comment by NAKKA-K** [comment]
> なぜかこのエラーが出る・・・これってsubmitボタン押したら何もエラーでないよね？

Actionのリクエストがミスってるんじゃない？

**Comment by NAKKA-K** [comment]
直した方がいい

**Comment by oya0831** [comment]
types.js
![image](https://user-images.githubusercontent.com/25961633/49912459-95379a00-fecd-11e8-966f-627f022597bf.png)
action.js
![image](https://user-images.githubusercontent.com/25961633/49912341-32de9980-fecd-11e8-97d4-54813de9749f.png)
reducer.js
![image](https://user-images.githubusercontent.com/25961633/49912391-5c97c080-fecd-11e8-9ddf-8417254a1bd9.png)
container.js
![image](https://user-images.githubusercontent.com/25961633/49912430-7fc27000-fecd-11e8-886c-f600b94ae985.png)
![image](https://user-images.githubusercontent.com/25961633/49912412-6e796380-fecd-11e8-906a-418387c12d06.png)
Header.jsx
![image](https://user-images.githubusercontent.com/25961633/49912600-024b2f80-fece-11e8-99b8-21cb9e4b9dcc.png)
![image](https://user-images.githubusercontent.com/25961633/49912611-0aa36a80-fece-11e8-96df-b8f224448203.png)

UserRegister.jsx
![image](https://user-images.githubusercontent.com/25961633/49912249-ea26e080-fecc-11e8-97f3-e80dcdb84a2b.png)

画像のところでthis.props.registerがずっとundefinedになったままで全然進まない・・・。
あとpromisevalueから個別にPOSTされた値がどうだったかを受け取ろうとしたけど調べたら原則無理っぽかったから結局ステータスだけ受け取ってエラー表示させようと思ってるけどどんな感じでエラー表示させたらいいやろか。このissueではとりあえずエラーですとかそんなんだけでいい感じ？
ユーザ側がどの値がエラーやったんか見れんかったら使いにくいんじゃないかと思ったけど・・・。

**Comment by oya0831** [comment]
![image](https://user-images.githubusercontent.com/25961633/49913199-1001b480-fed0-11e8-8e26-8e01fa41b3f7.png)

あとdispatchされたあとに表示されるはずなのになぜかpropsのログ表示の方が早いのもなぜかわかってない・・・頭破裂しそう・・・・・。

**Comment by NAKKA-K** [comment]
fetchは非同期関数だからね。
`submitRegister`内の`requestUserRegister()`を呼び出すと、内部でfetchが非同期で走り出す。
それが終わる前に`if(successfulStatus(this.props.register))`が走ってundefinedになる。

あと、registerに入る値って`{"message": "You have been successfully registerd user! Let's login."}`だろうから、successfulStatusの引数には受け取れないよ。
ステータスコードを受け取る関数だから

**Comment by NAKKA-K** [comment]
POSTがうまくいかないのはちょっとよくわからないけど、fetch関数でなくてwrapFetchを使うようにしてみたらちょっとスッキリして原因がわかりやすくなるかも。

**Comment by oya0831** [comment]
あー、非同期だからif文のが先に実行されてたのかあ、u-22の音声再生機構思い出す・・・・・。

>あと、registerに入る値って{"message": "You have been successfully registerd user! Let's login."}だろうから、successfulStatusの引数には受け取れないよ。
ステータスコードを受け取る関数だから

action.jsのres.statusで表示させるとステータスの400が表示されたからそいつをregisterに渡すように書いてんけどもしやこれってちゃんと渡せない感じなの・・・！？
とりあえずwrapFetchというものを使ってみる！

**Comment by NAKKA-K** [comment]
あ、statuscodeをreducerに登録してるのか。
見間違いしてた。
それなら渡せるわ

**Comment by oya0831** [comment]
うーん・・・なぜかwrapFetchだと入力情報もちゃんと満たしてて返ってくるステータス200のはずやのに400が返ってきたりする

とりあえずfetchで正常に200か400かsubmitした後に返るようにしてコンソール表示するようにしたけど多少ゴリ押しなところある、submit1回押したらregisterがundefinedで2回目押すとちゃんとステータス返ってくる挙動がなんでなのかよくわかってない・・・

**Comment by NAKKA-K** [comment]
んー、使い方が間違ってる説ある？
PullReqに[WIP]つけて出したら見る。

**Comment by oya0831** [comment]
ちゃんと正常に動く方のfetch使った方でいい？それかwrapFetchに書き換えた方がいい？

**Comment by NAKKA-K** [comment]
あー、どっちでもいいや。
とりあえず見るだけだから。

両方見て欲しいなら、コミットログにだけ残しといて。
コミットログからコード見るから
