### ISSUE TITLE
メールアドレス未検証ユーザの扱いを考える

### ISSUE THREAD

**Issue by kento-oka** [NAKKA-K/bookbok#203]
メールアドレス未検証ユーザは機能を制限する必要があるのかどうかなどを考える

**Comment by kento-oka** [comment]
メール検証が済んでいないユーザのログインは認めない方針に！

**Comment by NAKKA-K** [comment]
現在までの未検証ユーザーはemailに問題がなさそうだったので、`>>> App\User::whereNull('email_verified_at')->update(['email_verified_at' => now()])`で認証済みとした

**Comment by kento-oka** [comment]
結論が出て修正を開始した
