### ISSUE TITLE
本の一覧APIから情報を取得して、本の一覧画面に表示する

### ISSUE THREAD

**Issue by NAKKA-K** [NAKKA-K/bookbok#30]
[本の詳細画面タスク](https://github.com/NAKKA-K/bookbok/issues/29#issue-378094397)と大体同じ。
URLは`http://localhost:8000/api/books/`

**Comment by oya0831** [comment]
http://0.0.0.0:8000/booklistでのみ表示させたいねんけどどういう風に書いたらいいのかちょっとわかんないので教えてくだせえ。今の状態だとどのページにもブックリストが出てくるから・・・。
containerを加工しないといけないって書いてたけどcook-todoを参考にした書き方でcontainer.jsでdispatchしても表示されないのがなぜかわかんない・・・。index.jsxに直で書くなら全然表示される。

**Comment by oya0831** [comment]
どうでもいいけどコメントがurlになってて笑ってしまった。

**Comment by NAKKA-K** [comment]
どういう状態かいまいち掴めないな。
containers.jsとHeader.jsのコードを貼って欲しい

**Comment by oya0831** [comment]
面接練習あるから終わったら貼るわ

**Comment by oya0831** [comment]
Header.jsxの変えた部分
![image](https://user-images.githubusercontent.com/25961633/48693786-ea112900-ec1d-11e8-98b1-aa9d56b22849.png)
![image](https://user-images.githubusercontent.com/25961633/48693800-f4cbbe00-ec1d-11e8-924f-ac50630cf5b6.png)

container.js
![image](https://user-images.githubusercontent.com/25961633/48693881-1e84e500-ec1e-11e8-8466-82dbfc8f460c.png)

**Comment by NAKKA-K** [comment]
BookListViewの画像もあとでお願い

**Comment by oya0831** [comment]
![image](https://user-images.githubusercontent.com/25961633/48743499-baf2ca00-eca6-11e8-8db8-3bffbfc87964.png)
遅れてすまぬうううう！

**Comment by oya0831** [comment]
解決しましたぜ
