### ISSUE TITLE
F: 本詳細ページにて、追加済みの本についても「本棚に追加」が表示され、追加済みの場合画面に何も現れないバグを修正する

### ISSUE THREAD

**Issue by NAKKA-K** [NAKKA-K/bookbok#409]
すでに追加されている場合は409エラーが帰ってくるので、それで判断する。

**Comment by NAKKA-K** [comment]
@sugino0708 @kento-oka すでに追加されているかどうかを判断するのがほぼ無理。
なにか解決策求む。
無理やりやるとすればisRegisteredみたいなAPIを用意してやる......?

**Comment by sugino0708** [comment]
ログインしているユーザに対しての表示の切り分けが問題なら
ログインユーザの情報をバックエンド側で取得してチェックしたうえで
該当ユーザがすでに本を追加しているかどうかのフラグを今のレスポンスに加えればいいんじゃなかろうか( ﾟДﾟ)？

Authファサード使えばログインしている場合はユーザ情報すっぱ抜けるでしょ(@_@)たぶん

**Comment by NAKKA-K** [comment]
あ、そっか
それで行こう！

あと考えるべきはbookオブジェクト以下に配置するべきか、book・reviewオブジェクトと同階層に配置するかだな。

**Comment by NAKKA-K** [comment]
せやな
```
book: {
  ...
  isRegistered: false,
}
```
という感じで含めるかね
